name: doctor
description: A new Flutter project.


# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  json_annotation: ^3.0.1
  dio: ^3.0.10
  # https://pub.dev/packages/flutter_easyloading
  flutter_easyloading: ^2.0.0
  shared_preferences: ^2.0.5
  # 下拉刷新 https://github.com/peng8350/flutter_pulltorefresh
  pull_to_refresh: ^1.6.4
#  pull_to_refresh:
#    git:
#      url: git@codeup.aliyun.com:5f45ce70d24814603933bc3a/e-medclouds-web-group/flutter_pulltorefresh.git
  # State
  provider: ^5.0.0
  # 常用工具 https://github.com/Sky24n/common_utils
  common_utils: ^1.2.1

  # 进度条 https://pub.dev/packages/percent_indicator
  percent_indicator: ^2.1.7+4

  #轮播图 https://pub.flutter-io.cn/packages/flutter_swiper#installation
  flutter_swiper: ^1.1.6
  flutter_picker:
    git:
      url: git://github.com/yangyxd/flutter_picker.git
      ref: e95d121f54faba889fbf8a850c86dd5cf4aa5c5a

  # 图片查看器 https://pub.flutter-io.cn/packages/photo_view
  photo_view: ^0.10.2
  path_provider: ^2.0.1
  keyboard_visibility:
    git:
      url: git@codeup.aliyun.com:5f45ce70d24814603933bc3a/e-medclouds-web-group/flutter_keyboard_visibility.git
  # 解析html标签
  # flutter_html: ^1.0.2

  # third_app
  # 启动第三方appflu
  url_launcher: ^5.7.2

  device_info: ^2.0.0
  package_info: ^0.4.3

  open_file: ^3.0.1

  # 视频播放
  video_player: ^2.0.2
  # chewie: ^0.9.10
  screen: 0.0.5

  # 图片选择
  wechat_assets_picker: 5.0.3
  wechat_camera_picker: 2.1.0

  image_picker: 0.7.3

  # 图片占位符
  transparent_image: ^1.0.0

  #图片截取
  image_crop: ^0.3.4
  # 滚动到指数＃
  scroll_to_index: ^1.0.6

  # 该组件已在项目中重写
  # spinner_input: ^0.1.2

  # 监听网络变化 https://pub.flutter-io.cn/packages/connectivity
  connectivity: ^2.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  # toast
  toast: ^0.1.5
  # 文件预览插件
  flutter_file_preview:
    git:
      url: git@codeup.aliyun.com:5f45ce70d24814603933bc3a/e-medclouds-web-group/flutter_file_preview.git
      ref: 1.0.2
  # 图片压缩
  flutter_image_compress:
    git:
      url: git@codeup.aliyun.com:5f45ce70d24814603933bc3a/e-medclouds-web-group/flutter_image_compress.git
  # 文件路径url 操作
  path: ^1.7.0
  permission_handler: ^5.0.1+1
  event_bus: ^1.1.1
  http_manager:
    git:
      url: git@codeup.aliyun.com:5f45ce70d24814603933bc3a/http_manager.git
      ref: 1.0.6
  qr_code_scanner: ^0.3.5

dependency_overrides:
  http_parser: 4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.3
  json_serializable: ^3.4.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: myIcons
      fonts:
        - asset: assets/fonts/iconfont.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
